name: myenv
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.10
  - pandas
  - numpy
  - conda-forge::yfinance
  - scikit-learn
  - matplotlib
  - seaborn